openapi: 3.0.1
info:
  version: 1.0.0
  title: "DecksterlibApi"
paths: { }
components:
  schemas:
    ProtocolXXXDecksterMessage:
      type: object
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
    ProtocolXXXDecksterRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterMessage'
        - type: object
      discriminator:
        propertyName: type
    ProtocolXXXDecksterNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterMessage'
        - type: object
      discriminator:
        propertyName: type
    ProtocolXXXDecksterResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterMessage'
        - type: object
      discriminator:
        propertyName: type
    HandshakeXXXConnectMessage:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterMessage'
        - type: object
      discriminator:
        propertyName: type
    UnoXXXUnoRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterRequest'
        - type: object
      discriminator:
        propertyName: type
    UnoXXXUnoResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterResponse'
        - type: object
      discriminator:
        propertyName: type
    UnoXXXUnoGameNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterNotification'
        - type: object        
      discriminator:
        propertyName: type
    CrazyEightsXXXCrazyEightsRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterRequest'
        - type: object
      discriminator:
        propertyName: type
    CrazyEightsXXXCrazyEightsResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterResponse'
        - type: object
      discriminator:
        propertyName: type
    CrazyEightsXXXCrazyEightsNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterNotification'
        - type: object        
      discriminator:
        propertyName: type
    ChatRoomXXXChatRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterRequest'
        - type: object
      discriminator:
        propertyName: type
    ChatRoomXXXChatNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterNotification'
        - type: object
          properties:
            sender:
              type: string
            message:
              type: string
    ChatRoomXXXChatResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterResponse'
        - type: object
    HandshakeXXXHelloSuccessMessage:
      type: object
      allOf:
        - $ref: '#/components/schemas/HandshakeXXXConnectMessage'
        - type: object
          properties:
            player:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: object
                points:
                  type: integer
                  format: int32
            connectionId:
              type: object
    CommonXXXPlayerData:
      type: object
      properties:
        name:
          type: string
        id:
          type: object
        points:
          type: integer
          format: int32
    SystemXXXGuid:
      type: object
    HandshakeXXXConnectSuccessMessage:
      type: object
      allOf:
        - $ref: '#/components/schemas/HandshakeXXXConnectMessage'
        - type: object
    HandshakeXXXConnectFailureMessage:
      type: object
      allOf:
        - $ref: '#/components/schemas/HandshakeXXXConnectMessage'
        - type: object
          properties:
            errorMessage:
              type: string
    CommonXXXFailureResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ProtocolXXXDecksterResponse'
        - type: object
          properties:
            message:
              type: string
    UnoXXXUnoFailureResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoResponse'
        - type: object
          properties:
            message:
              type: string
    UnoXXXUnoSuccessResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoResponse'
        - type: object
    UnoXXXUnoCardResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoResponse'
        - type: object
          properties:
            card:
              type: object
              properties:
                color:
                  type: string
                value:
                  type: string
    UnoXXXUnoCard:
      type: object
      properties:
        color:
          type: string
        value:
          type: string
    UnoXXXPlayerViewOfUnoGame:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoResponse'
        - type: object
          properties:
            cards:
              type: array
              items:
                $ref: '#/components/schemas/UnoXXXUnoCard'
            topOfPile:
              type: object
              properties:
                color:
                  type: string
                value:
                  type: string
            currentSuit:
              type: string
            stockPileCount:
              type: integer
              format: int32
            discardPileCount:
              type: integer
              format: int32
            otherPlayers:
              type: array
              items:
                $ref: '#/components/schemas/UnoXXXOtherUnoPlayer'
    UnoXXXOtherUnoPlayer:
      type: object
      properties:
        name:
          type: string
        numberOfCards:
          type: integer
          format: int32
    UnoXXXPutCardRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoRequest'
        - type: object
          properties:
            card:
              type: object
              properties:
                color:
                  type: string
                value:
                  type: string
    UnoXXXPutWildRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoRequest'
        - type: object
          properties:
            card:
              type: object
              properties:
                color:
                  type: string
                value:
                  type: string
            newColor:
              type: string
    UnoXXXReadyToPlayRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoRequest'
        - type: object
    UnoXXXDrawCardRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoRequest'
        - type: object
      discriminator:
        propertyName: type
    UnoXXXPassRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoRequest'
        - type: object
    UnoXXXUnoCardsResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoResponse'
        - type: object
          properties:
            card:
              type: object
              properties:
                color:
                  type: string
                value:
                  type: string
    UnoXXXPlayerPutCardNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoGameNotification'
        - type: object
          properties:
            player:
              type: object
              properties:
                name:
                  type: string
                numberOfCards:
                  type: integer
                  format: int32
            card:
              type: object
              properties:
                color:
                  type: string
                value:
                  type: string
    UnoXXXPlayerPutWildNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoGameNotification'
        - type: object
          properties:
            player:
              type: object
              properties:
                name:
                  type: string
                numberOfCards:
                  type: integer
                  format: int32
            card:
              type: object
              properties:
                color:
                  type: string
                value:
                  type: string
            newColor:
              type: string
    UnoXXXPlayerDrewCardNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoGameNotification'
        - type: object
          properties:
            player:
              type: object
              properties:
                name:
                  type: string
                numberOfCards:
                  type: integer
                  format: int32
    UnoXXXPlayerPassedNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoGameNotification'
        - type: object
          properties:
            player:
              type: object
              properties:
                name:
                  type: string
                numberOfCards:
                  type: integer
                  format: int32
    UnoXXXItsYourTurnNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoGameNotification'
        - type: object
          properties:
            playerViewOfGame:
              type: object
              allOf:
                - $ref: '#/components/schemas/UnoXXXUnoResponse'
                - type: object
                  properties:
                    cards:
                      type: array
                      items:
                        $ref: '#/components/schemas/UnoXXXUnoCard'
                    topOfPile:
                      type: object
                      properties:
                        color:
                          type: string
                        value:
                          type: string
                    currentSuit:
                      type: string
                    stockPileCount:
                      type: integer
                      format: int32
                    discardPileCount:
                      type: integer
                      format: int32
                    otherPlayers:
                      type: array
                      items:
                        $ref: '#/components/schemas/UnoXXXOtherUnoPlayer'
    UnoXXXGameStartedNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoGameNotification'
        - type: object
          properties:
            players:
              type: array
              items:
                $ref: '#/components/schemas/CommonXXXPlayerData'
    UnoXXXGameEndedNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/UnoXXXUnoGameNotification'
        - type: object
          properties:
            players:
              type: array
              items:
                $ref: '#/components/schemas/CommonXXXPlayerData'
    CrazyEightsXXXPutCardRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsRequest'
        - type: object
          properties:
            card:
              type: object
              properties:
                rank:
                  type: integer
                  format: int32
                suit:
                  type: string
    CommonXXXCard:
      type: object
      properties:
        rank:
          type: integer
          format: int32
        suit:
          type: string
    CrazyEightsXXXPutEightRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsRequest'
        - type: object
          properties:
            card:
              type: object
              properties:
                rank:
                  type: integer
                  format: int32
                suit:
                  type: string
            newSuit:
              type: string
    CrazyEightsXXXDrawCardRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsRequest'
        - type: object
    CrazyEightsXXXPassRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsRequest'
        - type: object
    CrazyEightsXXXCrazyEightsFailureResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsResponse'
        - type: object
          properties:
            message:
              type: string
    CrazyEightsXXXCardResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsResponse'
        - type: object
          properties:
            card:
              type: object
              properties:
                rank:
                  type: integer
                  format: int32
                suit:
                  type: string
    CrazyEightsXXXPlayerPutCardNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsNotification'
        - type: object
          properties:
            playerId:
              type: object
            card:
              type: object
              properties:
                rank:
                  type: integer
                  format: int32
                suit:
                  type: string
    CrazyEightsXXXPlayerPutEightNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsNotification'
        - type: object
          properties:
            playerId:
              type: object
            card:
              type: object
              properties:
                rank:
                  type: integer
                  format: int32
                suit:
                  type: string
            newSuit:
              type: string
    CrazyEightsXXXPlayerDrewCardNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsNotification'
        - type: object
          properties:
            playerId:
              type: object
    CrazyEightsXXXPlayerPassedNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsNotification'
        - type: object
          properties:
            playerId:
              type: object
    CrazyEightsXXXItsYourTurnNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsNotification'
        - type: object
          properties:
            playerViewOfGame:
              type: object
              allOf:
                - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsResponse'
                - type: object
                  properties:
                    cards:
                      type: array
                      items:
                        $ref: '#/components/schemas/CommonXXXCard'
                    topOfPile:
                      type: object
                      properties:
                        rank:
                          type: integer
                          format: int32
                        suit:
                          type: string
                    currentSuit:
                      type: string
                    stockPileCount:
                      type: integer
                      format: int32
                    discardPileCount:
                      type: integer
                      format: int32
                    otherPlayers:
                      type: array
                      items:
                        $ref: '#/components/schemas/CrazyEightsXXXOtherCrazyEightsPlayer'
    CrazyEightsXXXPlayerViewOfGame:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsResponse'
        - type: object
          properties:
            cards:
              type: array
              items:
                $ref: '#/components/schemas/CommonXXXCard'
            topOfPile:
              type: object
              properties:
                rank:
                  type: integer
                  format: int32
                suit:
                  type: string
            currentSuit:
              type: string
            stockPileCount:
              type: integer
              format: int32
            discardPileCount:
              type: integer
              format: int32
            otherPlayers:
              type: array
              items:
                $ref: '#/components/schemas/CrazyEightsXXXOtherCrazyEightsPlayer'
    CrazyEightsXXXOtherCrazyEightsPlayer:
      type: object
      properties:
        name:
          type: string
        numberOfCards:
          type: integer
          format: int32
    CrazyEightsXXXGameStartedNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsNotification'
        - type: object
          properties:
            playerViewOfGame:
              type: object
              allOf:
                - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsResponse'
                - type: object
                  properties:
                    cards:
                      type: array
                      items:
                        $ref: '#/components/schemas/CommonXXXCard'
                    topOfPile:
                      type: object
                      properties:
                        rank:
                          type: integer
                          format: int32
                        suit:
                          type: string
                    currentSuit:
                      type: string
                    stockPileCount:
                      type: integer
                      format: int32
                    discardPileCount:
                      type: integer
                      format: int32
                    otherPlayers:
                      type: array
                      items:
                        $ref: '#/components/schemas/CrazyEightsXXXOtherCrazyEightsPlayer'
    CrazyEightsXXXGameEndedNotification:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsNotification'
        - type: object
          properties:
            players:
              type: array
              items:
                $ref: '#/components/schemas/CommonXXXPlayerData'
    CrazyEightsXXXCrazyEightsSuccessResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrazyEightsXXXCrazyEightsResponse'
        - type: object
    ChatRoomXXXSendChatMessage:
      type: object
      allOf:
        - $ref: '#/components/schemas/ChatRoomXXXChatRequest'
        - type: object
          properties:
            message:
              type: string